### ISSUE TITLE
Avoid requiring . when running paths

### ISSUE THREAD

**Issue by kirbyfan64** [rakitzis/rc#44]
The title probably doesn't make much sense, so here's an example: 

``` 
$ path/app
``` 

This works in bash, but it doesn't in rc unless . is in $path. I understand why this would be useful, but it can be really irritating, too. I'm using rc as the scripting language in my project [IsolateKit](https://github.com/kirbyfan64/isolatekit), and this would be a really nice addition!

**Comment by muennich** [comment]
Whats wrong with `$ ./path/app`?

**Comment by TobyGoodwin** [comment]
Interesting project, and delighted that you're using **rc**!

But I don't think there's anything to fix here. In **rc**: if a command starts with `/` it's absolute, otherwise we search `$path`. That's a simpler rule than **sh**, which I think is: if it start with `/` it's absolute, if it contains `/` it's relative to the cwd, otherwise we search `$PATH`.

This was used in Plan 9, as I understand it, to implement subcommands. In the Linux world, `git` is a wrapper, but in the Plan 9 world (had it existed there) it would simply be a directory `/bin/git/` and you'd say `git/commit ...` etc etc

**Comment by rakitzis** [comment]
NB: "asbolute" pathnames may also start with `./` and `../`
